services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: omybott-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: omybottdb
    volumes:
      - omybott_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d omybottdb"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  omybott_pgdata:
