spring:
  application:
    name: omybott
  datasource:
    url: jdbc:postgresql://localhost:5432/omybottdb
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect