spring:
  application:
    name: omybott
  datasource:
    url: jdbc:postgresql://localhost:5432/omybottdb
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      name: aryan
      password: admin
    oauth2:
      client:
        registration:
          google:
            client-id: testId
            client-secret: testSecret
  ai:
    ollama:
      base-url: http://192.168.29.214:11434
      chat:
        options:
          model: qwen3:0.6b
      embedding:
        options:
          model: nomic-embed-text

jwt:
  secretKey: qwertyuiopasdfghjklzxcvbnmmnbvcxzlkjhgfdsapiuytrewq
deploy:
  env: development
logging:
  level:
    root: DEBUG
    org.springframework.ai:
      chat.client: DEBUG